version: "3.8"

services:
    basaran:
        image: hyperonym/basaran:0.14.1
        restart: always
        environment:
            MODEL: "bigscience/bloomz-560m"
            SERVER_MODEL_NAME: "bloomz-560m"
            MODEL_HALF_PRECISION: "true"
            CUDA_MEMORY_FRACTION: "1.0"
        ports:
            - "80:80"
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
